create table AccessToken (id bigint not null auto_increment, accessToken varchar(255), timeout integer not null, updatetime bigint not null, primary key (id))
create table Admin (id bigint not null auto_increment, name varchar(255) not null, password varchar(255) not null, primary key (id))
create table Dishes (id bigint not null auto_increment, name varchar(255), primary key (id))
create table DishesSnapShot (id bigint not null auto_increment, name varchar(255), dishes_id bigint, primary key (id))
create table DishesSnapShot_OptionItem (DishesSnapShot_id bigint not null, optionItems_id bigint not null)
create table Message (id bigint not null auto_increment, content varchar(255), createTime bigint not null, event varchar(255), eventKey varchar(255), fromUserName varchar(255), msgId varchar(255), msgType varchar(255), toUserName varchar(255), primary key (id))
create table Option (id bigint not null auto_increment, name varchar(255), dishes_id bigint, primary key (id))
create table OptionItem (id bigint not null auto_increment, name varchar(255), price double precision not null, option_id bigint, primary key (id))
create table Orders (id bigint not null auto_increment, address varchar(255), dishes varchar(255), name varchar(255), openid varchar(255), telephone varchar(255), primary key (id))
create table User (openId varchar(255) not null, address varchar(255), telephone varchar(255), primary key (openId))
alter table Admin drop constraint UK_neu4frbbxvyq4gvaji5uagnuo
alter table Admin add constraint UK_neu4frbbxvyq4gvaji5uagnuo  unique (name)
alter table DishesSnapShot_OptionItem drop constraint UK_3mqs6qowne5sg1cgye9vhwg1n
alter table DishesSnapShot_OptionItem add constraint UK_3mqs6qowne5sg1cgye9vhwg1n  unique (optionItems_id)
create index createTimeIndex on Message (createTime)
alter table DishesSnapShot add constraint FK_od45gm5umeaewqdjyx0yup0hh foreign key (dishes_id) references Dishes (id)
alter table DishesSnapShot_OptionItem add constraint FK_3mqs6qowne5sg1cgye9vhwg1n foreign key (optionItems_id) references OptionItem (id)
alter table DishesSnapShot_OptionItem add constraint FK_42glgpbqp13ndi2pm9jb9oly9 foreign key (DishesSnapShot_id) references DishesSnapShot (id)
alter table Message add constraint FK_lxd4e1hxvg4dlgrbpvjavr3hs foreign key (fromUserName) references User (openId)
alter table Option add constraint FK_7w2sknd4olk3r6vc5f7mhbjfk foreign key (dishes_id) references Dishes (id)
alter table OptionItem add constraint FK_8wqmc1fnmil6fvh1lpw04wmgn foreign key (option_id) references Option (id)
